sudo: required

services: docker

env:
  matrix:
    - VERSION=11.0
    - VERSION=10.0
    - VERSION=9.0
    - VERSION=11.0 BATTERIES=True
    - VERSION=10.0 BATTERIES=True
    - VERSION=9.0 BATTERIES=True

script:
  - make VERSION=$VERSION build
  - make VERSION=$VERSION test

after_success:
  - travis/publish.sh
